import 'ids.dart';
import 'weapon_definitions.dart';

class WeaponLevelDefinition {
  const WeaponLevelDefinition({
    required this.damage,
    required this.cooldownSeconds,
    required this.range,
    required this.projectileCount,
    required this.pierce,
    required this.chainCount,
    required this.knockback,
    required this.displayEffect,
    this.durationSeconds = 0,
    this.slowFraction = 0,
  });

  final double damage;
  final double cooldownSeconds;
  final double range;
  final int projectileCount;
  final int pierce;
  final int chainCount;
  final double knockback;
  final String displayEffect;
  final double durationSeconds;
  final double slowFraction;
}

const weaponLevels = <WeaponId, List<WeaponLevelDefinition>>{
  hwandoSlash: [
    WeaponLevelDefinition(
      damage: 8,
      cooldownSeconds: 0.72,
      range: 58,
      projectileCount: 1,
      pierce: 0,
      chainCount: 0,
      knockback: 45,
      displayEffect: '피해 8, 범위 58',
    ),
    WeaponLevelDefinition(
      damage: 10,
      cooldownSeconds: 0.72,
      range: 68,
      projectileCount: 1,
      pierce: 0,
      chainCount: 0,
      knockback: 50,
      displayEffect: '피해 10, 범위 +10',
    ),
    WeaponLevelDefinition(
      damage: 12,
      cooldownSeconds: 0.60,
      range: 68,
      projectileCount: 1,
      pierce: 0,
      chainCount: 0,
      knockback: 55,
      displayEffect: '재사용 시간 0.60초',
    ),
    WeaponLevelDefinition(
      damage: 15,
      cooldownSeconds: 0.60,
      range: 82,
      projectileCount: 1,
      pierce: 0,
      chainCount: 0,
      knockback: 65,
      displayEffect: '피해 15, 범위 +14',
    ),
    WeaponLevelDefinition(
      damage: 18,
      cooldownSeconds: 0.52,
      range: 88,
      projectileCount: 2,
      pierce: 0,
      chainCount: 0,
      knockback: 75,
      displayEffect: '좌우 연속 베기 2회',
    ),
  ],
  gakgungShot: [
    WeaponLevelDefinition(
      damage: 7,
      cooldownSeconds: 1.05,
      range: 420,
      projectileCount: 1,
      pierce: 0,
      chainCount: 0,
      knockback: 10,
      displayEffect: '화살 1발, 피해 7',
    ),
    WeaponLevelDefinition(
      damage: 9,
      cooldownSeconds: 0.95,
      range: 420,
      projectileCount: 1,
      pierce: 0,
      chainCount: 0,
      knockback: 10,
      displayEffect: '피해 9, 재사용 시간 0.95초',
    ),
    WeaponLevelDefinition(
      damage: 10,
      cooldownSeconds: 0.95,
      range: 440,
      projectileCount: 1,
      pierce: 1,
      chainCount: 0,
      knockback: 12,
      displayEffect: '관통 +1',
    ),
    WeaponLevelDefinition(
      damage: 12,
      cooldownSeconds: 0.82,
      range: 460,
      projectileCount: 2,
      pierce: 1,
      chainCount: 0,
      knockback: 12,
      displayEffect: '화살 +1',
    ),
    WeaponLevelDefinition(
      damage: 15,
      cooldownSeconds: 0.72,
      range: 480,
      projectileCount: 2,
      pierce: 2,
      chainCount: 0,
      knockback: 15,
      displayEffect: '관통 +1, 첫 대상 추가 피해',
    ),
  ],
  talismanThrow: [
    WeaponLevelDefinition(
      damage: 8,
      cooldownSeconds: 1.40,
      range: 220,
      projectileCount: 1,
      pierce: 0,
      chainCount: 1,
      knockback: 8,
      displayEffect: '연쇄 1회, 원혼 추가 피해',
    ),
    WeaponLevelDefinition(
      damage: 10,
      cooldownSeconds: 1.30,
      range: 230,
      projectileCount: 1,
      pierce: 0,
      chainCount: 2,
      knockback: 8,
      displayEffect: '연쇄 +1',
    ),
    WeaponLevelDefinition(
      damage: 12,
      cooldownSeconds: 1.20,
      range: 240,
      projectileCount: 1,
      pierce: 0,
      chainCount: 3,
      knockback: 10,
      displayEffect: '연쇄 +1, 피해 12',
    ),
    WeaponLevelDefinition(
      damage: 14,
      cooldownSeconds: 1.10,
      range: 255,
      projectileCount: 1,
      pierce: 0,
      chainCount: 4,
      knockback: 10,
      displayEffect: '연쇄 +1, 탐색 범위 +15',
    ),
    WeaponLevelDefinition(
      damage: 17,
      cooldownSeconds: 1.00,
      range: 270,
      projectileCount: 2,
      pierce: 0,
      chainCount: 5,
      knockback: 12,
      displayEffect: '부적 +1, 연쇄 +1',
    ),
  ],
  thunderCrashBomb: [
    WeaponLevelDefinition(
      damage: 14,
      cooldownSeconds: 2.60,
      range: 70,
      projectileCount: 1,
      pierce: 0,
      chainCount: 0,
      knockback: 35,
      displayEffect: '폭발 범위 70, 피해 14',
    ),
    WeaponLevelDefinition(
      damage: 18,
      cooldownSeconds: 2.40,
      range: 82,
      projectileCount: 1,
      pierce: 0,
      chainCount: 0,
      knockback: 45,
      displayEffect: '폭발 범위 +12',
    ),
    WeaponLevelDefinition(
      damage: 22,
      cooldownSeconds: 2.20,
      range: 94,
      projectileCount: 1,
      pierce: 0,
      chainCount: 0,
      knockback: 55,
      displayEffect: '피해 22, 재사용 시간 2.20초',
    ),
    WeaponLevelDefinition(
      damage: 26,
      cooldownSeconds: 2.00,
      range: 106,
      projectileCount: 2,
      pierce: 0,
      chainCount: 0,
      knockback: 65,
      displayEffect: '폭발 +1',
    ),
    WeaponLevelDefinition(
      damage: 32,
      cooldownSeconds: 1.80,
      range: 120,
      projectileCount: 2,
      pierce: 0,
      chainCount: 0,
      knockback: 80,
      displayEffect: '피해 32, 폭발 범위 120',
    ),
  ],
  jangseungWard: [
    WeaponLevelDefinition(
      damage: 4,
      cooldownSeconds: .80,
      range: 72,
      projectileCount: 1,
      pierce: 0,
      chainCount: 0,
      knockback: 18,
      displayEffect: '결계 피해 4, 범위 72',
    ),
    WeaponLevelDefinition(
      damage: 5,
      cooldownSeconds: .70,
      range: 80,
      projectileCount: 1,
      pierce: 0,
      chainCount: 0,
      knockback: 22,
      displayEffect: '피해 5, 범위 80',
    ),
    WeaponLevelDefinition(
      damage: 6,
      cooldownSeconds: .60,
      range: 88,
      projectileCount: 1,
      pierce: 0,
      chainCount: 0,
      knockback: 28,
      displayEffect: '피해 6, 재사용 0.60초',
    ),
    WeaponLevelDefinition(
      damage: 7,
      cooldownSeconds: .52,
      range: 98,
      projectileCount: 1,
      pierce: 0,
      chainCount: 0,
      knockback: 34,
      displayEffect: '범위 98, 밀쳐내기 강화',
    ),
    WeaponLevelDefinition(
      damage: 9,
      cooldownSeconds: .45,
      range: 108,
      projectileCount: 1,
      pierce: 0,
      chainCount: 0,
      knockback: 42,
      displayEffect: '피해 9, 범위 108',
    ),
  ],
  singijeonVolley: [
    WeaponLevelDefinition(
      damage: 5,
      cooldownSeconds: 2.20,
      range: 460,
      projectileCount: 4,
      pierce: 0,
      chainCount: 0,
      knockback: 8,
      displayEffect: '신기전 4발 일제사격',
    ),
    WeaponLevelDefinition(
      damage: 6,
      cooldownSeconds: 2.00,
      range: 470,
      projectileCount: 5,
      pierce: 0,
      chainCount: 0,
      knockback: 8,
      displayEffect: '신기전 5발',
    ),
    WeaponLevelDefinition(
      damage: 7,
      cooldownSeconds: 1.80,
      range: 480,
      projectileCount: 6,
      pierce: 0,
      chainCount: 0,
      knockback: 10,
      displayEffect: '신기전 6발, 피해 7',
    ),
    WeaponLevelDefinition(
      damage: 8,
      cooldownSeconds: 1.60,
      range: 500,
      projectileCount: 7,
      pierce: 1,
      chainCount: 0,
      knockback: 10,
      displayEffect: '신기전 7발, 관통 +1',
    ),
    WeaponLevelDefinition(
      damage: 9,
      cooldownSeconds: 1.40,
      range: 520,
      projectileCount: 9,
      pierce: 1,
      chainCount: 0,
      knockback: 12,
      displayEffect: '신기전 9발 일제사격',
    ),
  ],
  frostFlask: [
    WeaponLevelDefinition(
      damage: 4,
      cooldownSeconds: 2.80,
      range: 60,
      projectileCount: 1,
      pierce: 0,
      chainCount: 0,
      knockback: 12,
      durationSeconds: 2.5,
      slowFraction: .20,
      displayEffect: '2.5초 서리 장판, 둔화 20%',
    ),
    WeaponLevelDefinition(
      damage: 5,
      cooldownSeconds: 2.60,
      range: 70,
      projectileCount: 1,
      pierce: 0,
      chainCount: 0,
      knockback: 14,
      durationSeconds: 3.0,
      slowFraction: .25,
      displayEffect: '3초 장판, 둔화 25%',
    ),
    WeaponLevelDefinition(
      damage: 6,
      cooldownSeconds: 2.40,
      range: 80,
      projectileCount: 1,
      pierce: 0,
      chainCount: 0,
      knockback: 16,
      durationSeconds: 3.5,
      slowFraction: .30,
      displayEffect: '3.5초 장판, 둔화 30%',
    ),
    WeaponLevelDefinition(
      damage: 7,
      cooldownSeconds: 2.20,
      range: 90,
      projectileCount: 1,
      pierce: 0,
      chainCount: 0,
      knockback: 18,
      durationSeconds: 4.0,
      slowFraction: .38,
      displayEffect: '4초 장판, 둔화 38%',
    ),
    WeaponLevelDefinition(
      damage: 8,
      cooldownSeconds: 2.00,
      range: 100,
      projectileCount: 1,
      pierce: 0,
      chainCount: 0,
      knockback: 20,
      durationSeconds: 4.5,
      slowFraction: .45,
      displayEffect: '4.5초 장판, 둔화 45%',
    ),
  ],
  windThunderFan: [
    WeaponLevelDefinition(
      damage: 9,
      cooldownSeconds: 1.60,
      range: 90,
      projectileCount: 1,
      pierce: 0,
      chainCount: 0,
      knockback: 50,
      displayEffect: '전방 번개 부채꼴',
    ),
    WeaponLevelDefinition(
      damage: 11,
      cooldownSeconds: 1.40,
      range: 102,
      projectileCount: 1,
      pierce: 0,
      chainCount: 0,
      knockback: 62,
      displayEffect: '피해 11, 범위 102',
    ),
    WeaponLevelDefinition(
      damage: 13,
      cooldownSeconds: 1.20,
      range: 114,
      projectileCount: 1,
      pierce: 0,
      chainCount: 0,
      knockback: 74,
      displayEffect: '밀쳐내기 강화',
    ),
    WeaponLevelDefinition(
      damage: 15,
      cooldownSeconds: 1.05,
      range: 126,
      projectileCount: 1,
      pierce: 0,
      chainCount: 0,
      knockback: 86,
      displayEffect: '피해 15, 범위 126',
    ),
    WeaponLevelDefinition(
      damage: 18,
      cooldownSeconds: .90,
      range: 140,
      projectileCount: 2,
      pierce: 0,
      chainCount: 0,
      knockback: 100,
      displayEffect: '앞뒤 번개 부채 2회',
    ),
  ],
};

WeaponLevelDefinition weaponLevelFor(WeaponId id, int level) {
  final levels = weaponLevels[id];
  if (levels == null) {
    throw ArgumentError.value(id, 'id', 'Unknown weapon');
  }
  if (level < 1 || level > levels.length) {
    throw RangeError.range(level, 1, levels.length, 'level');
  }

  return levels[level - 1];
}
